[text.english]
label = 'Text'

[option1]
[option1.english]
label = 'Option 1'

[option2]
[option2.english]
label = 'Option 2'

[option3]
[option3.english]
label = 'Option 3'

[option4]
[option4.english]
label = 'Option 4'

[correctOption]
isRequired = true
enum = ['Option 1', 'Option 2', 'Option 3', 'Option 4']
[correctOption.english]
label = 'Correct OOption'