[name]
sort = true
type = 'String'
autoSuggestion = true

[workshopCode]
type = 'String'
multiLingual = true

[startDate]
sort = true
type = 'date'
multiLingual = false

[endDate]
sort = true
type = 'date'
multiLingual = false

[quizQuestionCount]
type = 'number'

[numQuestionsTest]
type = 'number'