state = ['country.name']
city = ['state.name', 'state.country.name']
zone = ['states.name', 'states.country.name']
university = ['state.name', 'state.country.name']
college = ['state.name', 'state.country.name', 'university.name']
user = ['state.name', 'college.name', 'designation.name', 'workshops.name']
attendance = ['workshop.name', 'workshop.workshopCode']
poll = ['pollType']
user-poll = ['poll.day', 'poll.session', 'poll.pollType']